import './globals.scss';
import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { AuthProvider } from '@/context/auth';
import { ReduxProvider } from '@/store/ReduxProvider';
import Header from '@/components/header/header';
import Footer from '@/components/footer/footer';
import LayoutClient from './layoutClient';
import { getLocale, getMessages } from 'next-intl/server';

export const metadata: Metadata = {
  title: 'Rest Client',
  description: 'Generated by create next app',
};

export const dynamic = 'force-dynamic';

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let locale = 'en';
  let messages = {};
  try {
    locale = await getLocale();
    messages = await getMessages({ locale });
  } catch (error) {
    console.error('Error fetching locale or messages:', error);
  }

  return (
    <html lang={locale}>
      <body>
        <ReduxProvider>
          <AuthProvider>
            <NextIntlClientProvider locale={locale} messages={messages}>
              <LayoutClient>
                <header>
                  <Header />
                </header>
                <main>{children}</main>
                <footer>
                  <Footer />
                </footer>
              </LayoutClient>
            </NextIntlClientProvider>
          </AuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
